// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzT_NQOdKaBfPtDoPgvh2vYJaeZftl9H0',
    appId: '1:340237009291:web:e793eb6e06252ce0696f8e',
    messagingSenderId: '340237009291',
    projectId: 'test-login-d72a0',
    authDomain: 'test-login-d72a0.firebaseapp.com',
    storageBucket: 'test-login-d72a0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbAXbYJAo8TqVMJARZ97d42c8P3uKyfPE',
    appId: '1:340237009291:android:3f8f78c7c053e243696f8e',
    messagingSenderId: '340237009291',
    projectId: 'test-login-d72a0',
    storageBucket: 'test-login-d72a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoCD2Af0AhDaG9dT7iwX4NoRASGslYeB4',
    appId: '1:340237009291:ios:9f6c992bde98b00f696f8e',
    messagingSenderId: '340237009291',
    projectId: 'test-login-d72a0',
    storageBucket: 'test-login-d72a0.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoCD2Af0AhDaG9dT7iwX4NoRASGslYeB4',
    appId: '1:340237009291:ios:9f6c992bde98b00f696f8e',
    messagingSenderId: '340237009291',
    projectId: 'test-login-d72a0',
    storageBucket: 'test-login-d72a0.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzT_NQOdKaBfPtDoPgvh2vYJaeZftl9H0',
    appId: '1:340237009291:web:8841225bbcb78e4a696f8e',
    messagingSenderId: '340237009291',
    projectId: 'test-login-d72a0',
    authDomain: 'test-login-d72a0.firebaseapp.com',
    storageBucket: 'test-login-d72a0.firebasestorage.app',
  );
}
